# Generated by Django 4.2.5 on 2024-03-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_secret',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
